### ISSUE TITLE
2주차 진행

### ISSUE THREAD

**Issue by newoo** [CodeSoom/project-spring-1-newoo#3]
1. 이 앱을 언제 사용하나요?

새로운 모임들을 만들거나 어떤 모임들이 있는지 보고싶을 때 사용합니다.
만들어진 모임들을 수정하거나 삭제할 때 사용합니다.
모임앱에 가입하고 싶을 때 사용합니다.

2. 구체적인 사례는 무엇인가요?

앱을 시작하면 만들어진 모임들을 볼 수 있고, 원하는 모임이 없다면 추가로 만들 수 있다.
만들어진 모임은 수정하거나, 삭제할 수 있다.
모임앱에 가입하고, 로그인할 수 있다.

3. 이번 주가 지나면 사용자는 무엇을 할 수 있나요?

앱을 통해 모임리스트를 볼 수 있고, 모임에 대한 상세 내용도 볼 수 있다.
원하는 모임을 추가할 수 있고, 수정 및 삭제도 가능하다.
앱에 회원가입하고, 로그인할 수 있다.

4. 이번주 에 구현할 기능을 우선순위대로 작성해 주세요

- [ ] 새로운 모임을 추가하는 기능
- [ ] 모임리스트를 불러오는 기능
- [ ] 상세 모임 내용을 불러오는 기능
- [ ] 모임을 수정할 수 있는 기능
- [ ] 모임을 삭제할 수 있는 기능
- [ ] 회원가입할 수 있는 기능
- [ ] 로그인할 수 있는 기능

**Comment by hannut91** [comment]
기능 단위로 작게 나누신 것 같습니다 ㅎㅎ 기능, 즉 요구사항을 명시할 때 사용자가 어떤 가치를 얻을 수 있는지로 서술해보면 좋을 것 같습니다

예를들어

> 새로운 모임을 추가하는 기능 => 사용자는 새로운 모임을 열 수 있다.
> 모임리스트를 불러오는 기능 => 사용자는 모임 목록을 조회할 수 있다.
> 상세 모임 내용을 불러오는 기능 => 사용자는 모임에 대한 상세정보를 조회할 수 있다. => 사용자는 모임에 대한 날짜, 장소를 조회할 수 있다.

이렇게하면 요구사항이 개발자만 이해할 수 있는 것이 아닌 고객, 사용자가 이해할 수 있게 되고, 테스트 가능하며, 사용자가 해당 가치를 얻을 수 있으면 기능이 완료되므로 기능의 완료 조건도 명시할 수 있으며 동작하는 소프트웨어를 만들 수 있을거에요
